version: '3.8'

services:
  persona-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - VITE_DESTATIS_API_KEY=${VITE_DESTATIS_API_KEY}
      - VITE_DESTATIS_PASSWORD=${VITE_DESTATIS_PASSWORD}
      - VITE_EUROSTAT_API_KEY=${VITE_EUROSTAT_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s